name: Deploy

on:
  push:
    branches:
      - main

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: dswistowski/surge-sh-action@v1
        with:
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}